### ISSUE TITLE
[generator] Generator compiled using emcc is too large

### ISSUE THREAD

**Issue by yubing744** [bitseed/bitseed#13]
In the generator directory, use the following command:

···
     make clean && make build
···

The generated generator.wasm is about 148K

![image](https://github.com/bitseed/bitseed/assets/1449069/728dbfed-1d0a-4074-beca-7d634df7ca82)

**Comment by steelgeek091** [comment]
the following command will resolve this issue:
```
emcc -g0 -Oz -I/usr/local/include generator.cpp -sSTANDALONE_WASM=1 -sWASM=1 -s "EXPORTED_FUNCTIONS=['_inscribe_generate', '_inscribe_verify']" --no-entry -sDEFAULT_LIBRARY_FUNCS_TO_INCLUDE='$stringToUTF8' -s "EXPORTED_RUNTIME_METHODS=['cwrap']" -o generator.js -flto -fno-rtti -fno-exceptions
```
